# Generated by Django 5.1.6 on 2025-03-12 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('relationship_type', models.CharField(blank=True, choices=[('short_term', 'Short Term'), ('long_term', 'Long Term'), ('unsure', 'Still Trying to Figure Out')], max_length=20, null=True)),
                ('city', models.CharField(blank=True, choices=[('adrian', 'Adrian'), ('hudson', 'Hudson'), ('toledo', 'Toledo'), ('jackson', 'Jackson')], max_length=20, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='Height in feet (e.g., 5.9)', max_digits=4, null=True)),
                ('hobbies', models.CharField(blank=True, help_text='Comma-separated hobbies (e.g., bowling,movies,reading)', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
