# Generated by Django 5.1.6 on 2025-03-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('adrian', 'Adrian'), ('hudson', 'Hudson'), ('toledo', 'Toledo'), ('jackson', 'Jackson'), ('detroit', 'Detroit'), ('grand_rapids', 'Grand Rapids'), ('ann_arbor', 'Ann Arbor'), ('lansing', 'Lansing'), ('flint', 'Flint'), ('kalamazoo', 'Kalamazoo'), ('saginaw', 'Saginaw'), ('traverse_city', 'Traverse City'), ('muskegon', 'Muskegon'), ('port_huron', 'Port Huron')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
